name: Custom ROM Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git-core gnupg flex bison build-essential zip curl \
          zlib1g-dev libc6-dev-i386 libncurses5 x11proto-core-dev \
          libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
          xsltproc unzip fontconfig

    - name: Install repo
      run: |
        export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
        curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
        gpg --recv-keys 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
        curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} /usr/bin/repo

    - name: Set up rombuilds folder
      run: mkdir -p ~/rombuilds

    - name: Sync source code into rombuilds folder
      run: |
        cd ~/rombuilds
        repo init -u https://github.com/SuperiorExtended/manifest -b UDC
        repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync

    - name: Clone kernel source
      run: |
        cd ~/rombuilds
        git clone -b fog-r-oss https://github.com/alternoegraha/wwy_kernel_xiaomi_fog_rebase/ kernel/xiaomi/fog

    - name: Clone vendor tree
      run: |
        cd ~/rombuilds
        git clone -b fourteen https://github.com/alternoegraha/vendor_xiaomi_fog vendor/xiaomi/fog

    - name: Clone device tree
      run: |
        cd ~/rombuilds
        git clone -b fourteen-oss https://github.com/alternoegraha/device_xiaomi_fog device/xiaomi/fog

    - name: Source build environment
      run: |
        cd ~/rombuilds
        source build/envsetup.sh

    - name: Choose target
      run: lunch SuperiorExtended_fog-userdebug

    - name: Build ROM
      run: make bacon -j$(nproc --all)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        release_name: Release v1.0
        body: |
          This is the first release of the custom ROM.
        draft: false
        prerelease: false

    - name: Upload ROM artifact
      uses: actions/upload-artifact@v2
      with:
        name: custom-rom
        path: ~/rombuilds/out/target/product/your_device_codename/your-rom.zip
