name: Custom ROM Build

on:
  push:
    branches:
      - main  # Change this to your default branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Git Config
      run: |
        git config --global user.name "itsbuilderxxx"
        git config --global user.email "rafsanhasan064@gmail.com"

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python-is-python3 android-tools-adb android-tools-fastboot

    - name: Install Repo
      run: |
        mkdir -p ~/bin
        curl -o ~/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
        chmod +x ~/bin/repo
        export PATH=~/bin:$PATH

    - name: Set Up Build Environment
      run: |
        WORKSPACE=$(pwd)
        mkdir -p $WORKSPACE/android_source
        mkdir -p $WORKSPACE/rom_sources

    - name: Sync Android Source
      run: |
        cd $WORKSPACE/android_source
        repo init -u https://android.googlesource.com/platform/manifest -b android-14.0.0_r31
        repo sync -j$(nproc --all)

    - name: Sync ROM Sources
      run: |
        cd $WORKSPACE/rom_sources
        repo init -u https://github.com/RisingTechOSS/android -b fourteen
        repo sync -j$(nproc --all)

    - name: Source build/envsetup.sh
      run: |
        source $WORKSPACE/rom_sources/build/envsetup.sh

    - name: Clone Device Tree, Kernel, and Vendor
      run: |
        cd $WORKSPACE/rom_sources
        git clone -b <device_tree_branch> https://github.com/alternoegraha/device_xiaomi_fog device/xiaomi
        git clone -b <kernel_branch> <kernel_repo_URL> kernel/<kernel_name>
        git clone -b <vendor_branch> <vendor_repo_URL> vendor/<vendor_name>

    - name: Build ROM
      run: |
        cd $WORKSPACE/rom_sources
        lunch ROMNAME_<device_name>-userdebug
        m bacon -j$(nproc --all)

    - name: Create Release
      if: success()
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        body: |
          Custom ROM built successfully from commit: ${{ github.sha }}
          Add any additional release notes here.
        draft: false
        prerelease: false
